{% set raw_version = "2025-03-26" %}
{% set version = "2025.03.06" %} 

{% set sha256 = "c73240a73b8533c2d7309058b413fc42b9deb0eca4983a10a9f35e3a6a1d3df9" %}

package:
  name: rsat-core
  version: {{ version }}

build:
  run_exports:
    - {{ pin_subpackage('rsat-core', max_pin=None) }}
  number: 0
  skip: True  # [py2k]

source:
  url: https://github.com/rsa-tools/rsat-code/archive/refs/tags/{{ raw_version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - r-base      

  run:
    ## Python3      
    - python
    - numpy
    - scipy
    - matplotlib-base
    - httplib2
    - pygraphviz
    - snakemake
    - pyyaml
    - opencv

    ## R dependencies
    - r-base
    - r-gplots
    - r-jpeg
    - r-png
    - r-devtools
    - r-ggplot2
    - r-dynamictreecut
    - r-reshape2
    - r-dendextend
    - r-gridextra
    - r-egg
    - r-flux
    - r-zoo
    - r-rcolorbrewer
    - r-amap
    - r-rjsonio
    - r-dplyr
    - r-data.table

    ## R BioConductor dependencies
    - bioconductor-ctc
    - bioconductor-qvalue

    ## Perl dependencies
    - perl
    - perl-bioperl
    - perl-bio-das
    - perl-yaml
    - perl-cgi
    - perl-statistics-distributions
    - perl-math-cdf
    - perl-algorithm-cluster
    - perl-file-spec
    - perl-posix
    - perl-data-dumper
    - perl-digest-md5-file
    - perl-io-all
    - perl-object-insideout
    - perl-class-std-fast
    - perl-gd
    - perl-dbi
    - perl-dbd-mysql
    - perl-db-file
    - perl-lwp-simple
    - perl-json
    - perl-soap-lite
    - perl-xml-libxml
    - perl-xml-dom
    - perl-xml-parser
    - perl-log-log4perl
    - perl-number-format
    - perl-readonly
    - perl-rest-client
    - perl-http-tiny
    - perl-lockfile-simple
    - perl-util-properties
    - perl-ensembl-api
    - perl-ensembl-genomes
    - perl-parallel-forkmanager
    - perl-mce-shared

    ## Standalone tools
    - seqlogo
    - weblogo
    - bedtools
    - d3
    - blast
    - ghostscript
    - gnuplot
    - vmatch

    ## Not needed really, Web server only
    - perl-email-simple

test:
  commands:
    - "rsat -h"   ## test the RSAT command
    - "rsat oligo-analysis -h" ## Test a subcommand running a Perl script
    - "rsat random-seq -l 100 -n 2" ## Test a perl script
    - "rsat random-seq -l 100 -n 2 | rsat purge-sequence" ## Check the vmatch dependency of purge-sequence
    - "rsat random-motif -l 10" ## Test a subcommand running a python script
    - "rsat feature-map -h" ## check the GD dependency for feature-map
    # Check that the compiled executable are running (compiled C program, in the bin folder)
    - "rsat info-gibbs -h"
    - "rsat count-words -h"
    - "rsat matrix-scan-quick -h"
    - "rsat matrix-clustering -h" # Test if the specific Perl dependencies have been successfully included for this tool
    - "make -f ${PREFIX}/share/rsat/makefiles/subcommand_tests.mk randseq" ## Quick test for one Perl script
    - "make -f ${PREFIX}/share/rsat/makefiles/subcommand_tests.mk xygraph" ## test GD dependency

about:
  home: http://rsat.eu
  summary: "Regulatory Sequence Analysis Tools (RSAT)"
  license: GNU Affero General Public License v3
  license_file: LICENSE.txt
  description: "Detection and analysis of regulatory signals in non-coding sequences"

extra:
  identifiers:
    - biotools:rsat
    - doi:10.1093/nar/gky317
  notes: |
    This package installs RSAT with tools to analyse cis-regulatory elements:
    * motif discovery (support genome-wide data sets like ChIP-seq)
    * transcription factor binding motif analysis (quality assessment, comparisons and clustering)
    * comparative genomics
    * analysis of regulatory variations

    Documentation can be found at https://rsa-tools.github.io/installing-RSAT

    Note that this package does not include genome sequences nor DNA motif collections, 
    please check https://rsa-tools.github.io/installing-RSAT/RSAT-Docker/RSAT-Docker-tuto.html
    to learn how to add them in your system. 
